### ISSUE TITLE
"You are here” spot

### ISSUE THREAD

**Issue by cutout33** [ucdavis/wayfinding#22]
Hi,

Is it possible to have a "You are here” spot that indicates user`s current location? I mean that can be updated programmatically according to the user location on the map?

**Comment by AsmaSaid** [comment]
Hello,
With the available version is there a way to add a new starting point (Room)  programmatically ?

**Comment by jraller** [comment]
Can you explain a little more? Are you trying to change starting points or
add a new one that did not exist before? The first is in the API, the
second is not and would be best done with a change of the SVG file.
