### ISSUE TITLE
Map probelm

### ISSUE THREAD

**Issue by AsmaSaid** [ucdavis/wayfinding#26]
Hello,
after downloading the zip file and clicking on the index file the map wouldn't load !
I'm a beginner so I'm not sure should I upload it to a server is't a json thing?

**Comment by jraller** [comment]
Were you trying to use the demo locally?

**Comment by AsmaSaid** [comment]
No I've uploaded the files to a server below is the link

http://asmadevelopment.3eeweb.com/wayfinding-master/

thank you,

**Comment by jraller** [comment]
You don't have jQuery loaded.

**Comment by AsmaSaid** [comment]
My mistake. It's works perfectly now.
Thank you for this amazing plugin.
