### ISSUE TITLE
Need Help with understanding how the SVGs need to be constructed

### ISSUE THREAD

**Issue by skyrbe** [ucdavis/wayfinding#28]
Hi Guys,

I need some help in understanding the exact way in which the svg needs to be built. Can you please help me.

**Comment by eberon** [comment]
+1 I couldn't grok it at all, find doc, or read the code to understand the expectations in this area.

**Comment by skyrbe** [comment]
@eberon : Found a solution: In the simplest from, 
Layer 1
--Doors
  --Room1(Doors are again drawn using the line tool)
  --lcd.1(very important since the JS takes this as the starting point)
--Rooms
  --Room1
--Paths
  --Path1
  --Path2
  --Path3 and so on (Paths are something that you draw using the line tool.Make sure that the paths    intersect perfectly on the anchor points or else the routing won't work)
there should be one starting point and one room, the name of the room layer should be the name of the door
--Base(is the background images like lobby,reception etc , call them starting points, these are not mandatory)
--Portals(these will come into play only if you have multiple floors or such, not mandatory).

This worked for me, closing the issue. If you need any further assistance, send me a mail!

**Comment by jraller** [comment]
As soon as I get access to a recent copy of Illustrator I'll make the guide and put it up.

**Comment by skyrbe** [comment]
@jraller : Thanks,was the information I provided above close to what it should be?
