### ISSUE TITLE
This is not a issue, this is a request

### ISSUE THREAD

**Issue by skyrbe** [ucdavis/wayfinding#29]
Hi,

Will it be possible to pan the map along with the path, so as to show sort of a camera movement view in the map?

**Comment by jraller** [comment]
Have you tried the zoom feature (`zoomToRoute`)? My concern about panning along the route would be one of perhaps not showing enough of the context of the map to let people pick out waypoints to reference.

**Comment by skyrbe** [comment]
I will try that, thanks :-) By the way, do you think raspberry pi 'b' would be sufficient for this. Please keep in mind that our svgs are around 2 mb in size.

**Comment by jraller** [comment]
Without knowing more about the capabilities of the pi I'd start off looking at using the datastores. The current version has the capability to generate datastores by editing the /test/fixtures/datastores.html file to refer to your map collection and to your default map. Then consider editing start.txt if you don't want all to all routing and then run `grunt datastore` which will launch a local server and then prompt you for where to save the datastores. One you have these you can use the `dataStoreCache` option.
