### ISSUE TITLE
How to draw svg ? adobe illustrator or other tools?

### ISSUE THREAD

**Issue by bingchengcool** [ucdavis/wayfinding#32]

**Comment by jraller** [comment]
I've used Illustrator in the past, but do not have access to the latest
version to test it.

**Comment by bruninfante** [comment]
Hello jraller,
I have a question when you are making the path/elements, the order of each element on the layer is important or the only important thing is the pacement of the coordenates connecting in the exact same point (X,Y, Z)?
Thanks for the help, and amazing job with this project.

**Comment by jraller** [comment]
Placement of the end points with the same X and Y is important, and having the lines that make up paths be in the right group is important. Element order should not matter as the svg file is parsed and an internal model of it is used for the parts that aren't displayed to the screen.
