### ISSUE TITLE
Accessible is not showing correct route.

### ISSUE THREAD

**Issue by mayuriJ** [ucdavis/wayfinding#33]
Hello,
As per your comment specified, "accessible route takes the elevator rather than the stairs even though the path is longer". This saying is true but violated in some cases. For example, If route is from reception to R201 or lobby to R201, result is correct that is if accessible is true path uses elevator and if accessible is false path uses stair case. But when route is from conference room to R201, result is incorrect. Path is using only elevator in both the cases(accessible or non accessible). Same issue with route from reception to R202 or lobby to R202 or conference room to R202, in any case result is from elevator only.
Can you please help to solve this issue?

Thank You.

**Comment by jraller** [comment]
How are you measuring the length?

**Comment by mayuriJ** [comment]
For measuring the length and finding the path, I am using same calculation logic given in this jquery plugin. No any change.

**Comment by mayuriJ** [comment]
Hello,
I am measuring length using this formula
Distance  = sqrt{(x_2 -x_1)^2 + (y_2- y_1)^2}

**Comment by jraller** [comment]
Given the way that I set the paths in the demo it is shorter to take the
elevator from the conference room to 201.
