### ISSUE TITLE
How can i change Room 

### ISSUE THREAD

**Issue by farihulrouf** [ucdavis/wayfinding#50]
Dear Developer, i have created SVG file for new room with inkscape to replaced` demo_map_1.svg` but it dos'nt work .

**Comment by sunilkeshavamurthy** [comment]
Have you ensured that you have followed conventions as per the svg in the demo link ? http://ucdavis.github.io/wayfinding/

**Comment by farihulrouf** [comment]
I have tried and I want to change the svg file but do not work http://bl.ocks.org/cartoda/7a5cbd2f6193e7f73b41. What tools do you use?
